# Generated by Django 4.1.1 on 2022-09-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='core.habit')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.habit')),
            ],
        ),
    ]
