# Generated by Django 4.1.1 on 2022-09-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_amount',
            field=models.IntegerField(null=True),
        ),
    ]
