# Generated by Django 4.1.1 on 2022-09-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailyrecord_date_habit_goal_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='unit',
        ),
    ]
