# Generated by Django 4.1.1 on 2022-09-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dailyrecord_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='amount_completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
