# Generated by Django 4.1.1 on 2022-09-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dailyrecord_amount_completed_habit_created_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_constraint'),
        ),
    ]
